services:
  db:
    env_file: .env
    image: postgres:15
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=${DB_NAME?Variable not set}
    ports:
      - "5432:5432"
  cache:
    image: "redis:6.2-alpine"
    restart: unless-stopped
    command: --port 6379
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - app-db-data:/data

volumes:
  app-db-data:
